---
apiVersion: v1
kind: Secret
metadata:
  name: minio-test
  namespace: minio
stringData:
  endpoint: "http://minio.minio.svc:9000"
  bucket: "tempo"
  access_key_id: "tempo"
  access_key_secret: "supersecret"
type: Opaque