apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    app: prometheus
    component: prometheus-conf
data:
  prometheus-config.yaml: |
    scrape_configs:
      - job_name: 'otel-collector-metrics'
        scrape_interval: 10s
        static_configs:
          - targets: [ 'otel-collector:8888' ] # Metrics exposed by the collector itself
    
      - job_name: 'otel-collector-exporter-metrics'
        scrape_interval: 10s
        static_configs:
          - targets: [ 'otel-collector:8889' ] # Metrics exposed from underlined services
        metric_relabel_configs:
          - source_labels: [ exported_job ]
            target_label: application
            action: replace
          - action: labeldrop
            regex: exported_job