apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          args:
            - '--storage.tsdb.retention.time=24h'
            - '--config.file=/etc/prometheus/prometheus-config.yaml'
            - '--storage.tsdb.path=/prometheus/'
            - '--enable-feature=exemplar-storage'
            - '--web.enable-remote-write-receiver'
          volumeMounts:
            - name: prometheus-volume
              mountPath: /data
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-volume
          persistentVolumeClaim:
            claimName: pvc-prometheus
        - name: prometheus-config-volume
          configMap:
            name: prometheus-conf
            items:
              - key: prometheus-config.yaml
                path: prometheus-config.yaml