apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yml
  - deployment.yml
  - service.yml
  - cm.yml

labels:
  - includeSelectors: true
    pairs:
      app: prometheus
      component: prometheus