apiVersion: v1
kind: ConfigMap
metadata:
    name: tempo-conf
    labels:
        app.kubernetes.io/name: tempo
data:
    tempo.yaml: |
      server:
        http_listen_port: 3200
      
      distributor:
        log_received_spans:
          enabled: true # for debugging
        receivers:
          otlp:
            protocols:
              http:
              grpc:
      
      ingester:
        max_block_duration: 5m # cut the headblock when this much time passes
      
      compactor:
        compaction:
          block_retention: 1h # overall Tempo trace retention
      
      storage:
        trace:
          backend: s3
          s3:
            endpoint: 'minio.monitoring:9000'
            bucket: 'tempo'
            access_key: 'tempo'
            secret_key: 'supersecret'
            insecure: true
      
      overrides:
        metrics_generator_processors: [ service-graphs, span-metrics ]
