apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
spec:
  type: ClusterIP
  ports:
    - name: grpc-tempo-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: tempo-otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: grafana-datasource-port
      port: 3200
      protocol: TCP
      targetPort: 3200
  selector:
    app.kubernetes.io/name: tempo