apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cm.yml
  - service.yml
  - deployment.yml

labels:
  - includeSelectors: true
    pairs:
      app: opentelemetry
      component: otel-collector