---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  labels:
    app.kubernetes.io/name: grafana
data:
  tempo.yaml: |-
    apiVersion: 1
    datasources:
      - name: 'Tempo'
        type: 'tempo'
        uid: 'tempo'
        access: 'proxy'
        editable: true
        isDefault: true
        url: 'http://tempo.monitoring:3200'
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: 'loki'
          tracesToLogsV2:
            datasourceUid: 'loki'
          tracesToMetrics:
            datasourceUid: 'prometheus'
          serviceMap:
            datasourceUid: 'prometheus'
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: 'loki'
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: 'Loki'
        type: 'loki'
        uid: 'loki'
        access: 'proxy'
        editable: false
        url: 'http://loki.monitoring:3100'
        jsonData:
          derivedFields:
            - datasourceUid: 'tempo'
              matcherRegex: '"traceid":"([a-f0-9]{32})"'
              name: 'TraceID'
              url: "$${__value.raw}"
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: 'Prometheus'
        uid: 'prometheus'
        type: 'prometheus'
        access: 'proxy'
        editable: false
        url: 'http://prometheus:9090'
        jsonData:
          httpMethod: GET
          exemplarTraceIdDestinations:
            - datasourceUid: 'tempo'
              name: trace_id
          manageAlerts: true
          maxLines: 1000
